site :opscode
cookbook 'apache2'
cookbook 'aws'
cookbook 'aws-cloud-watch-cli-tools'
cookbook 'aws_developer_tools'
cookbook 'ganglia'
cookbook 'logwatch'
cookbook 'mysql'
cookbook 'nagios'
cookbook 'networking_basic', '= 0.0.6'
cookbook 'nginx'
cookbook 'ntp'
cookbook 'selinux'
cookbook 'timezone'
cookbook 'yum'
